# Generated by Django 5.2 on 2025-04-19 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('idespecialidad', models.IntegerField(db_column='idEspecialidad', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'especialidad',
            },
        ),
        migrations.CreateModel(
            name='Estadobox',
            fields=[
                ('idestadobox', models.IntegerField(db_column='idestadoBox', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=90, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'estadobox',
            },
        ),
        migrations.CreateModel(
            name='Tipobox',
            fields=[
                ('idtipobox', models.IntegerField(db_column='idtipoBox', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'tipobox',
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('idbox', models.IntegerField(db_column='idBox', primary_key=True, serialize=False)),
                ('numerobox', models.IntegerField(blank=True, db_column='numeroBox', null=True)),
                ('ubicacionbox', models.CharField(blank=True, db_column='ubicacionBox', max_length=200, null=True)),
                ('estadobox_idestadobox', models.ForeignKey(db_column='estadoBox_idestadoBox', on_delete=django.db.models.deletion.DO_NOTHING, to='ZephyApp.estadobox')),
                ('tipobox_idtipobox', models.ForeignKey(db_column='tipoBox_idtipoBox', on_delete=django.db.models.deletion.DO_NOTHING, to='ZephyApp.tipobox')),
            ],
            options={
                'db_table': 'box',
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('idprofesional', models.IntegerField(db_column='idProfesional', primary_key=True, serialize=False)),
                ('rutprofesional', models.CharField(blank=True, db_column='rutProfesional', max_length=45, null=True)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('apellido', models.CharField(blank=True, max_length=90, null=True)),
                ('email', models.CharField(blank=True, max_length=320, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('especialidad_idespecialidad', models.ForeignKey(db_column='Especialidad_idEspecialidad', on_delete=django.db.models.deletion.DO_NOTHING, to='ZephyApp.especialidad')),
            ],
            options={
                'db_table': 'profesional',
            },
        ),
        migrations.CreateModel(
            name='Boxprofesional',
            fields=[
                ('idboxprofesionalcol', models.CharField(db_column='idBoxProfesionalcol', max_length=45, primary_key=True, serialize=False)),
                ('fechaasignacion', models.DateField(blank=True, db_column='fechaAsignacion', null=True)),
                ('fechatermino', models.DateField(blank=True, db_column='fechaTermino', null=True)),
                ('horarioinicio', models.TimeField(blank=True, db_column='horarioInicio', null=True)),
                ('horariofin', models.TimeField(blank=True, db_column='horarioFin', null=True)),
                ('box_idbox', models.ForeignKey(db_column='Box_idBox', on_delete=django.db.models.deletion.DO_NOTHING, to='ZephyApp.box')),
                ('profesional_idprofesional', models.ForeignKey(db_column='Profesional_idProfesional', on_delete=django.db.models.deletion.DO_NOTHING, to='ZephyApp.profesional')),
            ],
            options={
                'db_table': 'boxprofesional',
            },
        ),
    ]
